### ISSUE TITLE
Default value of `lvm_lvopts` fails to create logical volume

### ISSUE THREAD

**Issue by sbesson** [openmicroscopy/infrastructure#25]
The default value of `lvm_lvopts` which is `null` - see https://github.com/openmicroscopy/infrastructure/pull/11 gives runtime errors of type

```
fatal: [web-qa-staging.openmicroscopy.org]: FAILED! => {"changed": false, "err": "  Volume group \"None\" not found\n", "failed": true, "invocation": {"module_args": {"lv": "jenkins-workdir", "opts": null, "size": "500m", "vg": "VolGroup00"}, "module_name": "lvol"}, "msg": "Creating logical volume 'jenkins-workdir' failed", "rc": 5}
```

Removing `opts` from the `lvm-partition` role allows to complete the task.

**Comment by manics** [comment]
#28 which also uses `lvm-partition` works for me after rebasing onto the current head d8a5120

**Comment by manics** [comment]
@sbesson Is this fixed now?

**Comment by sbesson** [comment]
My comment from Friday has been lost it seems. I have not retried since. Given https://github.com/openmicroscopy/infrastructure/issues/25#issuecomment-155055034, I will close this issue and we can reopen if appropriate.
